apiVersion: v1
kind: ConfigMap
metadata:
  name: mic-sid-postgres-config
  labels:
    app: mic-sid-postgres
data:
  PGDATA: /var/lib/postgresql/data/mic-sid-pgdata
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: scBktWufX4kX
  POSTGRES_SERVICE: mic-sid-postgres-service
---
apiVersion: v1
kind: Pod
metadata:
  name: mic-sid-postgres
  labels:
    app: mic-sid-postgres
spec:
  volumes:
    - name: mic-sid-postgredb-volume
      persistentVolumeClaim:
        claimName: pvc-mic-sid-postgres
  containers:
    - name: mic-sid-postgres
      image: postgres:14-alpine
      imagePullPolicy: Always
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: mic-sid-postgres-config
      volumeMounts:
        - name: mic-sid-postgredb-volume
          mountPath: /var/lib/postgresql/data
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: mic-sid-postgres-service
spec:
  selector:
    app: mic-sid-postgres
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: NodePort            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-sid-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mic-sid-app
  template:
    metadata:
      labels:
        app: mic-sid-app
    spec:
      containers:
        - name: mic-sid-app
          image: southamerica-east1-docker.pkg.dev/applied-mystery-342719/tccpucminastiagojoao-repo/mic-sid-microservice:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: mic-sid-postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: mic-sid-service
  labels:
    app: mic-sid-service
spec:
  selector:
    app: mic-sid-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
