apiVersion: v1
kind: Pod
metadata:
  name: jbpm-server-full
  labels:
    app: jbpm-server-full
spec:
  securityContext:
    fsGroup: 1000
  volumes:
    - name: niogit-jbpm-server-full
      persistentVolumeClaim:
        claimName: pvc-jbpm-server-full
        readOnly: false
  containers:
    - name: jbpm-server-full
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 2Gi
      image: jboss/jbpm-server-full:7.61.0.Final
      imagePullPolicy: Always
      ports:
        - containerPort: 8001
        - containerPort: 8080
      volumeMounts:
        - name: niogit-jbpm-server-full
          mountPath: /opt/jboss/wildfly/bin/.niogit
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-jbpm-server-full
spec:
  type: LoadBalancer
  selector:
    app: jbpm-server-full
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
