apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jbpm-server-full
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: node-port-jbpm-server-full
spec:
  type: NodePort
  selector:
    app: jbpm-server-full
  ports:
    - name: "8001"
      nodePort: 30801
      port: 8001
      targetPort: 8001
    - name: "8080"
      nodePort: 30880
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: jbpm-server-full
  labels:
    app: jbpm-server-full
spec:
  securityContext:
    fsGroup: 1000
  volumes:
    - name: niogit-jbpm-server-full
      persistentVolumeClaim:
        claimName: pvc-jbpm-server-full
        readOnly: false
  containers:
    - name: jbpm-server-full
      image: jboss/jbpm-server-full:7.61.0.Final
      ports:
        - containerPort: 8001
        - containerPort: 8080
      volumeMounts:
        - mountPath: /opt/jboss/wildfly/bin/.niogit
          name: niogit-jbpm-server-full
